name: Git Actions CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read hello.txt
        run: cat hello.txt
    
build_job:
  needs: test_job
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Node js.
      uses: actions/setup-node@v4
      with:
        node-version: '22'


        