name: GIT Actions CI/CD

on:
  push:
    branches:
      - main
      

  pull_request:
    branches:
      - main


job:
  read_hello_file:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Read hello.txt
        run: cat hello.txt